// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqxVo9mSRDr9N9xBGZzG80esdK9xoIyk0',
    appId: '1:169467470274:web:f8b075c2e2c528676f365b',
    messagingSenderId: '169467470274',
    projectId: 'todo-list-a3214',
    authDomain: 'todo-list-a3214.firebaseapp.com',
    storageBucket: 'todo-list-a3214.appspot.com',
    measurementId: 'G-3BHQ54K53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMsGz8ypkulZ_jpa1z4zYE9FvabWv_LxA',
    appId: '1:169467470274:android:23d3f38ba79d79896f365b',
    messagingSenderId: '169467470274',
    projectId: 'todo-list-a3214',
    storageBucket: 'todo-list-a3214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0XeBu8HwLqd3z0OnjgJKXirocWEOCaJc',
    appId: '1:169467470274:ios:36747cbfdec1c7006f365b',
    messagingSenderId: '169467470274',
    projectId: 'todo-list-a3214',
    storageBucket: 'todo-list-a3214.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0XeBu8HwLqd3z0OnjgJKXirocWEOCaJc',
    appId: '1:169467470274:ios:36747cbfdec1c7006f365b',
    messagingSenderId: '169467470274',
    projectId: 'todo-list-a3214',
    storageBucket: 'todo-list-a3214.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqxVo9mSRDr9N9xBGZzG80esdK9xoIyk0',
    appId: '1:169467470274:web:7c67c47320a8e7e96f365b',
    messagingSenderId: '169467470274',
    projectId: 'todo-list-a3214',
    authDomain: 'todo-list-a3214.firebaseapp.com',
    storageBucket: 'todo-list-a3214.appspot.com',
    measurementId: 'G-19TV16HM0Y',
  );
}
